const txt = '{"name":"Jennie", "last":"Nichols", "age":30}'
const txt2 = '{"street":"Valwood Pkwy", "number": 8929, "city":"Billings"}'
const txt3 = '{"primaria":"Escuela Don Orione", "secundaria": "Escuela Comercial", "terciaria":"UTN"}'
const txt4 = '{"exper":"2010/15 Glovant - 2015/20 Boogle - 2020/22 Fasevook"}'
const obj = JSON.parse(txt);
const obj2 = JSON.parse(txt2);
const obj3 = JSON.parse(txt3);
const obj4 = JSON.parse(txt4);
document.getElementById("results").innerHTML = "Nombre: " + obj.name + " Apellido: " +  obj.last + " Edad: " + obj.age ;
document.getElementById("results2").innerHTML = "Calle: " +obj2.street + " Numero: " + obj2.number + " Ciudad: " + obj2.city;
document.getElementById("results3").innerHTML = "Primaria: " +obj3.primaria + " Secundaria: " + obj3.secundaria + " Terciaria: " + obj3.terciaria;
document.getElementById("results4").innerHTML = "Experiencia Laboral: " + obj4.exper ;